# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAppOneSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAppOneSwift
  pod 'RGNetworking', :path => "../RGNetworking"
  pod 'ProgressHUD', :git => "https://github.com/relatedcode/ProgressHUD.git"

  target 'MyAppOneSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppOneSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
