# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RGBankAccount' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RGBankAccount
  pod 'RGBankAccountLib', :path => "../RGBankAccountLib"
  pod 'ProgressHUD', :git => "https://github.com/relatedcode/ProgressHUD.git"
  pod 'iOS-Color-Picker'

  target 'RGBankAccountTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RGBankAccountUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
